[theme]
base = "light"
primaryColor = "#1D6FE8"
backgroundColor = "#F7F8FB"
secondaryBackgroundColor = "#EDEFF4"
textColor = "#2E3140"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
